// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zootact.Infrastructure.Data;

#nullable disable

namespace Zootact.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ZootactDbContext))]
    [Migration("20260418060050_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.GameMoveEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CapturedPiece")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("captured_piece");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FromPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("from_position");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("integer")
                        .HasColumnName("move_number");

                    b.Property<string>("PieceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("piece_type");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<long>("PositionHash")
                        .HasColumnType("bigint")
                        .HasColumnName("position_hash");

                    b.Property<int>("TimeSpentMs")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_ms");

                    b.Property<string>("ToPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("to_position");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "MoveNumber");

                    b.ToTable("game_moves", (string)null);
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.MatchAnalysisEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisJson")
                        .HasColumnType("text")
                        .HasColumnName("analysis_json");

                    b.Property<string>("AntiCheatJson")
                        .HasColumnType("text")
                        .HasColumnName("anti_cheat_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("match_analysis", (string)null);
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.MatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BlueEloAfter")
                        .HasColumnType("integer")
                        .HasColumnName("blue_elo_after");

                    b.Property<int>("BlueEloBefore")
                        .HasColumnType("integer")
                        .HasColumnName("blue_elo_before");

                    b.Property<Guid>("BluePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blue_player_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int>("IncrementMs")
                        .HasColumnType("integer")
                        .HasColumnName("increment_ms");

                    b.Property<int>("InitialTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("initial_time_ms");

                    b.Property<int?>("RedEloAfter")
                        .HasColumnType("integer")
                        .HasColumnName("red_elo_after");

                    b.Property<int>("RedEloBefore")
                        .HasColumnType("integer")
                        .HasColumnName("red_elo_before");

                    b.Property<Guid>("RedPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("red_player_id");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<string>("ResultReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result_reason");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("InProgress")
                        .HasColumnName("status");

                    b.Property<string>("TimeControl")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("time_control");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id");

                    b.HasIndex("RedPlayerId");

                    b.HasIndex("Status")
                        .HasFilter("status = 'InProgress'");

                    b.HasIndex("WinnerId");

                    b.HasIndex("BluePlayerId", "RedPlayerId");

                    b.ToTable("matches", null, t =>
                        {
                            t.HasCheckConstraint("chk_different_players", "blue_player_id <> red_player_id");
                        });
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("firebase_uid");

                    b.Property<int>("ForestPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1200)
                        .HasColumnName("forest_points");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("ForestPoints")
                        .IsDescending();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.UserStatsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AvgMoveTimeMs")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("avg_move_time_ms");

                    b.Property<int>("Draws")
                        .HasColumnType("integer")
                        .HasColumnName("draws");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<int>("TotalGames")
                        .HasColumnType("integer")
                        .HasColumnName("total_games");

                    b.Property<long>("TotalPlayTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_play_time_ms");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("WinStreakBest")
                        .HasColumnType("integer")
                        .HasColumnName("win_streak_best");

                    b.Property<int>("WinStreakCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("win_streak_current");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.GameMoveEntity", b =>
                {
                    b.HasOne("Zootact.Infrastructure.Data.Entities.MatchEntity", "Match")
                        .WithMany("Moves")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zootact.Infrastructure.Data.Entities.UserEntity", "Player")
                        .WithMany("Moves")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.MatchAnalysisEntity", b =>
                {
                    b.HasOne("Zootact.Infrastructure.Data.Entities.MatchEntity", "Match")
                        .WithOne("Analysis")
                        .HasForeignKey("Zootact.Infrastructure.Data.Entities.MatchAnalysisEntity", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.MatchEntity", b =>
                {
                    b.HasOne("Zootact.Infrastructure.Data.Entities.UserEntity", "BluePlayer")
                        .WithMany("BlueMatches")
                        .HasForeignKey("BluePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zootact.Infrastructure.Data.Entities.UserEntity", "RedPlayer")
                        .WithMany("RedMatches")
                        .HasForeignKey("RedPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zootact.Infrastructure.Data.Entities.UserEntity", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BluePlayer");

                    b.Navigation("RedPlayer");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.UserStatsEntity", b =>
                {
                    b.HasOne("Zootact.Infrastructure.Data.Entities.UserEntity", "User")
                        .WithOne("Stats")
                        .HasForeignKey("Zootact.Infrastructure.Data.Entities.UserStatsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.MatchEntity", b =>
                {
                    b.Navigation("Analysis");

                    b.Navigation("Moves");
                });

            modelBuilder.Entity("Zootact.Infrastructure.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("BlueMatches");

                    b.Navigation("Moves");

                    b.Navigation("RedMatches");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
